---
:ems:
  :ems_azure_stack:
    # How long before giving up on establishing connection with Azure Stack API URL.
    :api_connection_timeout: 5.seconds

    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :update:
          :critical:
            - !ruby/regexp /^Administrative_Microsoft.(Compute|Resources)_.+_write_(Succeeded|Failed)$/
          :detail:
            - !ruby/regexp /^Administrative_Microsoft.(Compute|Resources)_.+_write_.+$/
        :deletion:
          :critical:
            - !ruby/regexp /^Administrative_Microsoft.(Compute|Resources)_.+_delete_(Succeeded|Failed)$/
          :detail:
            - !ruby/regexp /^Administrative_Microsoft.(Compute|Resources)_.+_delete_.+$/
        :power:
          :critical:
            - !ruby/regexp /^Administrative_Microsoft.(Compute|Resources)_.+_(restart|start|deallocate)_(Succeeded|Failed)$/
          :detail:
            - !ruby/regexp /^Administrative_Microsoft.(Compute|Resources)_.+_(restart|start|deallocate)_.+$/
        :status:
          :critical:
            - !ruby/regexp /^(ServiceHealth|ResourceHealth|Alert|AutoScale|Security|Recommendation)_.+$/
        :storage:
          :critical:
            - !ruby/regexp /^Administrative_Microsoft.Storage_.+$/
        :network:
          :critical:
            - !ruby/regexp /^Administrative_Microsoft.Network_.+$/

:http_proxy:
  :azure_stack:
    :host:
    :password:
    :port:
    :user:

:ems_refresh:
  :azure_stack:
    :inventory_object_refresh: true
  :azure_stack_network:
    :inventory_object_refresh: true

:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_azure_stack:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_azure_stack: {}
      :ems_refresh_worker:
        :ems_refresh_worker_azure_stack: {}
        :ems_refresh_worker_azure_stack_network: {}

